# Generated by Django 3.1.6 on 2021-02-07 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0002_auto_20210206_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classify',
            name='category',
        ),
        migrations.RemoveField(
            model_name='classify',
            name='label',
        ),
        migrations.RemoveField(
            model_name='classify',
            name='percentage',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
